<a href="https://colab.research.google.com/github/BGourav05/DATA-SCIENCE-AIML-USING-PYTHON/blob/main/Day2_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
animals=['Tiger','Bear','Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [ ]:
sports={'Archery':'Bhutan','Golf':
        'Scotland','sumo':'Japan','Taekwando':'sk'}
s=pd.Series(sports)
s

Archery        Bhutan
Golf         Scotland
sumo            Japan
Taekwando          sk
dtype: object

In [ ]:
s.values

array(['Bhutan', 'Scotland', 'Japan', 'sk'], dtype=object)

In [ ]:
s.index

Index(['Archery', 'Golf', 'sumo', 'Taekwando'], dtype='object')

In [ ]:
s=pd.Series(['Tiger','Bear','Moose'],
            index=['India','America','Canada'])
s

India      Tiger
America     Bear
Canada     Moose
dtype: object

In [ ]:
sports={'Archery':'Bhutan','Golf':
        'Scotland','sumo':'Japan','Taekwando':'sk'}
s=pd.Series(sports,index=['Golf',
                          'sumo','Hockey'])
s

Golf      Scotland
sumo         Japan
Hockey         NaN
dtype: object

In [ ]:
s.iloc[2]

nan

In [ ]:
s.loc['Golf']

'Scotland'

In [ ]:
ser.iloc[2]

NameError: name 'ser' is not defined

In [ ]:
sports={99:'bhutan,
100:'Scotland'}

SyntaxError: unterminated string literal (detected at line 1) (1031021443.py, line 1)

In [ ]:
import numpy as np
import pandas as pd
s=pd.Series(np.random.randint(0,1000,10000))
print(s.head())
print(s.tail())

0    346
1    968
2     22
3    986
4    395
dtype: int64
9995    796
9996    909
9997    755
9998    616
9999    864
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
s=pd.Series(np.random.randint(0,1000,10000))
print(s.head(3))
print(s.tail(7))

0    767
1     27
2    973
dtype: int64
9993    132
9994    970
9995    357
9996    191
9997    327
9998     98
9999    475
dtype: int64

# Pandas Series Exercises

This section covers answers and practical examples for the questions provided.

### Q1. Create pandas series from different data types like list, numpy array and dictionary.

In [ ]:
import numpy as np
import pandas as pd

# 1. From a List
list_data = ['Apple', 'Banana', 'Cherry']
series_list = pd.Series(list_data)
print("Series from List:")
display(series_list)

# 2. From a NumPy Array
array_data = np.array([10, 20, 30, 40])
series_array = pd.Series(array_data, index=['a', 'b', 'c', 'd'])
print("\nSeries from NumPy Array:")
display(series_array)

# 3. From a Dictionary
dict_data = {'France': 'Paris', 'Germany': 'Berlin', 'Italy': 'Rome'}
series_dict = pd.Series(dict_data)
print("\nSeries from Dictionary:")
display(series_dict)

Series from List:

0     Apple
1    Banana
2    Cherry
dtype: object

Series from NumPy Array:

a    10
b    20
c    30
d    40
dtype: int64

Series from Dictionary:

France      Paris
Germany    Berlin
Italy        Rome
dtype: object

### Q2. How to get the items of Series A not present in Series B?

In [ ]:
series_a = pd.Series([1, 2, 3, 4, 5])
series_b = pd.Series([4, 5, 6, 7, 8])

# Get items in series_a not present in series_b
not_present = series_a[~series_a.isin(series_b)]
print("Items in Series A not in Series B:")
display(not_present)

Items in Series A not in Series B:

0    1
1    2
2    3
dtype: int64

### Q3. How to get intersection of two series?

In [ ]:
# We can use numpy.intersect1d or find items present in both
intersection = pd.Series(np.intersect1d(series_a, series_b))
print("Intersection of Series A and Series B:")
display(intersection)

Intersection of Series A and Series B:

0    4
1    5
dtype: int64

### Q4. How to get union of two series?

In [ ]:
# Get union of all unique elements from both series
union = pd.Series(np.union1d(series_a, series_b))
print("Union of Series A and Series B:")
display(union)

Union of Series A and Series B:

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
# Simplest forms of operations on two Series
series_a = pd.Series([1, 2, 3, 4, 5])
series_b = pd.Series([4, 5, 6, 7, 8])

# Q2: Items in A not in B
diff = series_a[~series_a.isin(series_b)]
print("A not in B:\n", diff.tolist())

# Q3: Intersection (common items)
inter = np.intersect1d(series_a, series_b)
print("Intersection:\n", inter.tolist())

# Q4: Union (all unique items combined)
union = np.union1d(series_a, series_b)
print("Union:\n", union.tolist())

A not in B:
 [1, 2, 3]
Intersection:
 [4, 5]
Union:
 [1, 2, 3, 4, 5, 6, 7, 8]